#include <easy3d/renderer/shader_manager.h>
#include <easy3d/renderer/shader_program.h>
#include <memory>
#include <sstream> // __str__
#include <string>
#include <utility>
#include <vector>

#include <functional>
#include <pybind11/pybind11.h>
#include <string>
#include <pybind11/stl.h>


#ifndef BINDER_PYBIND11_TYPE_CASTER
	#define BINDER_PYBIND11_TYPE_CASTER
	PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>, false)
	PYBIND11_DECLARE_HOLDER_TYPE(T, T*, false)
	PYBIND11_MAKE_OPAQUE(std::shared_ptr<void>)
#endif

void bind_easy3d_renderer_shader_program(pybind11::module_& m)
{
	{ // easy3d::ShaderProgram file:easy3d/renderer/shader_program.h line:77
		pybind11::class_<easy3d::ShaderProgram, std::shared_ptr<easy3d::ShaderProgram>> cl(m, "ShaderProgram", "OpenGL Shader Compilation\n\n \n\n To use the shader program class, you need to do the following:\n - Call load_shader_from_code(ShaderProgram::VERTEX, vert_file) to create vertex shader and\n        load_shader_from_code(ShaderProgram::FRAGMENT, frag_file) to create fragment shader\n        (you may also need to create other types of shaders depending on your needs).\n - Call set_attrib_name(ShaderProgram::POSITION, \"position\") for vertex attribute \"position\".\n        You may also need to set other attributes like normal, color, etc. To know what vertex\n        attributes need to be set, check your shader code or call print_active_attributes().\n - Call link_program() to link the program.\n\n For rendering\n - Call bind();\n - Call set_uniform() to set all the necessary uniforms. You may also need to call set_block(),\n        set_block_uniform(), and/or set_block_uniform_array_element(). To know what uniforms need to\n        be set, check your shader code or call print_active_uniforms(), print_active_uniform_blocks().\n - Call the drawable's draw() function\n - Call release();\n\n To retrieve the model view projection matrix, call camera's  modelViewProjectionMatrix() ");
		cl.def( pybind11::init( [](){ return new easy3d::ShaderProgram(); } ), "doc" );
		cl.def( pybind11::init<const std::string &>(), pybind11::arg("name") );


		pybind11::enum_<easy3d::ShaderProgram::AttribType>(cl, "AttribType", pybind11::arithmetic(), "")
			.value("POSITION", easy3d::ShaderProgram::POSITION)
			.value("COLOR", easy3d::ShaderProgram::COLOR)
			.value("NORMAL", easy3d::ShaderProgram::NORMAL)
			.value("TEXCOORD", easy3d::ShaderProgram::TEXCOORD)
			.export_values();


		pybind11::enum_<easy3d::ShaderProgram::ShaderType>(cl, "ShaderType", pybind11::arithmetic(), "")
			.value("VERTEX", easy3d::ShaderProgram::VERTEX)
			.value("FRAGMENT", easy3d::ShaderProgram::FRAGMENT)
			.value("GEOMETRY", easy3d::ShaderProgram::GEOMETRY)
			.value("TESS_CONTROL", easy3d::ShaderProgram::TESS_CONTROL)
			.value("TESS_EVALUATION", easy3d::ShaderProgram::TESS_EVALUATION)
			.value("COMPUTE", easy3d::ShaderProgram::COMPUTE)
			.value("NUM_SHADER_TYPES", easy3d::ShaderProgram::NUM_SHADER_TYPES)
			.export_values();

		cl.def_static("is_supported", (bool (*)()) &easy3d::ShaderProgram::is_supported, "C++: easy3d::ShaderProgram::is_supported() --> bool");
		cl.def("set_name", (void (easy3d::ShaderProgram::*)(const std::string &)) &easy3d::ShaderProgram::set_name, "C++: easy3d::ShaderProgram::set_name(const std::string &) --> void", pybind11::arg("name"));
		cl.def("name", (const std::string & (easy3d::ShaderProgram::*)() const) &easy3d::ShaderProgram::name, "C++: easy3d::ShaderProgram::name() const --> const std::string &", pybind11::return_value_policy::automatic);
		cl.def("set_verbose", (void (easy3d::ShaderProgram::*)(bool)) &easy3d::ShaderProgram::set_verbose, "Sets true to log any issues found.\n\nC++: easy3d::ShaderProgram::set_verbose(bool) --> void", pybind11::arg("v"));
		cl.def("get_program", (unsigned int (easy3d::ShaderProgram::*)() const) &easy3d::ShaderProgram::get_program, "Returns the program index.\n\nC++: easy3d::ShaderProgram::get_program() const --> unsigned int");
		cl.def("clear", (void (easy3d::ShaderProgram::*)()) &easy3d::ShaderProgram::clear, "Removes (deletes) all shaders\n\nC++: easy3d::ShaderProgram::clear() --> void");
		cl.def("load_shader_from_file", [](easy3d::ShaderProgram &o, enum easy3d::ShaderProgram::ShaderType const & a0, const std::string & a1) -> bool { return o.load_shader_from_file(a0, a1); }, "", pybind11::arg("st"), pybind11::arg("file_name"));
		cl.def("load_shader_from_file", (bool (easy3d::ShaderProgram::*)(enum easy3d::ShaderProgram::ShaderType, const std::string &, const std::string &)) &easy3d::ShaderProgram::load_shader_from_file, "Loads the text in the file to the source of the specified shader\n \n\n one of the enum values of ShaderType\n \n\n the full path of the file where the source is to be found\n \n\n the include identifier string (e.g., \"#include\")\n\nC++: easy3d::ShaderProgram::load_shader_from_file(enum easy3d::ShaderProgram::ShaderType, const std::string &, const std::string &) --> bool", pybind11::arg("st"), pybind11::arg("file_name"), pybind11::arg("inc_id"));
		cl.def("load_shader_from_code", (bool (easy3d::ShaderProgram::*)(enum easy3d::ShaderProgram::ShaderType, const std::string &)) &easy3d::ShaderProgram::load_shader_from_code, "Loads the code to the source of the specified shader\n \n\n one of the enum values of ShaderType\n \n\n the string of the shader source code\n\nC++: easy3d::ShaderProgram::load_shader_from_code(enum easy3d::ShaderProgram::ShaderType, const std::string &) --> bool", pybind11::arg("st"), pybind11::arg("code"));
		cl.def("set_attrib_name", (void (easy3d::ShaderProgram::*)(enum easy3d::ShaderProgram::AttribType, const std::string &) const) &easy3d::ShaderProgram::set_attrib_name, "Defines semantics for the input vertex attributes. This is required for other libraries to know how to\n send data to the shader.\n \n\n The semantic of the attribute\n \n\n The name of the vertex attribute\n \n\n To specify a location for an attribute you must do it prior to linking the program, or, if the\n      program is already linked, to link it again afterwards (call method link_program)\n\nC++: easy3d::ShaderProgram::set_attrib_name(enum easy3d::ShaderProgram::AttribType, const std::string &) const --> void", pybind11::arg("at"), pybind11::arg("name"));
		cl.def("set_attrib_names", (void (easy3d::ShaderProgram::*)(const class std::vector<struct std::pair<enum easy3d::ShaderProgram::AttribType, std::string> > &) const) &easy3d::ShaderProgram::set_attrib_names, "C++: easy3d::ShaderProgram::set_attrib_names(const class std::vector<struct std::pair<enum easy3d::ShaderProgram::AttribType, std::string> > &) const --> void", pybind11::arg("attributes"));
		cl.def("link_program", (bool (easy3d::ShaderProgram::*)()) &easy3d::ShaderProgram::link_program, "Prepares program for usage. Links it and collects information about uniform variables and uniform blocks.\n\nC++: easy3d::ShaderProgram::link_program() --> bool");
		cl.def("set_program_output", (void (easy3d::ShaderProgram::*)(int, const std::string &) const) &easy3d::ShaderProgram::set_program_output, "Bind a user-defined varying out variable to a fragment shader color number\n Note: linking is required for this operation to take effect\n (call method prepare_program afterwards)\n \n\n The fragment color number\n \n\n The name of the fragment's shader variable\n\nC++: easy3d::ShaderProgram::set_program_output(int, const std::string &) const --> void", pybind11::arg("index"), pybind11::arg("name"));
		cl.def("program_output", (int (easy3d::ShaderProgram::*)(const std::string &) const) &easy3d::ShaderProgram::program_output, "Returns the fragment shader color number bound to a user-defined varying out variable\n Note: linking is required for this operation to take effect\n (call method prepare_program afterwards)\n \n\n name of the fragment's shader variable\n \n\n the fragment color number\n\nC++: easy3d::ShaderProgram::program_output(const std::string &) const --> int", pybind11::arg("name"));
		cl.def("bind", (void (easy3d::ShaderProgram::*)() const) &easy3d::ShaderProgram::bind, "Starts using the program.\n\nC++: easy3d::ShaderProgram::bind() const --> void");
		cl.def("set_uniform", (class easy3d::ShaderProgram * (easy3d::ShaderProgram::*)(const std::string &, const void *)) &easy3d::ShaderProgram::set_uniform, "C++: easy3d::ShaderProgram::set_uniform(const std::string &, const void *) --> class easy3d::ShaderProgram *", pybind11::return_value_policy::automatic, pybind11::arg("name"), pybind11::arg("value"));
		cl.def("set_uniform", (class easy3d::ShaderProgram * (easy3d::ShaderProgram::*)(const std::string &, int)) &easy3d::ShaderProgram::set_uniform, "C++: easy3d::ShaderProgram::set_uniform(const std::string &, int) --> class easy3d::ShaderProgram *", pybind11::return_value_policy::automatic, pybind11::arg("name"), pybind11::arg("value"));
		cl.def("set_uniform", (class easy3d::ShaderProgram * (easy3d::ShaderProgram::*)(const std::string &, unsigned int)) &easy3d::ShaderProgram::set_uniform, "C++: easy3d::ShaderProgram::set_uniform(const std::string &, unsigned int) --> class easy3d::ShaderProgram *", pybind11::return_value_policy::automatic, pybind11::arg("name"), pybind11::arg("value"));
		cl.def("set_uniform", (class easy3d::ShaderProgram * (easy3d::ShaderProgram::*)(const std::string &, float)) &easy3d::ShaderProgram::set_uniform, "C++: easy3d::ShaderProgram::set_uniform(const std::string &, float) --> class easy3d::ShaderProgram *", pybind11::return_value_policy::automatic, pybind11::arg("name"), pybind11::arg("value"));
		cl.def("set_block", (class easy3d::ShaderProgram * (easy3d::ShaderProgram::*)(const std::string &, const void *)) &easy3d::ShaderProgram::set_block, "Sets a uniform block as a whole\n\nC++: easy3d::ShaderProgram::set_block(const std::string &, const void *) --> class easy3d::ShaderProgram *", pybind11::return_value_policy::automatic, pybind11::arg("name"), pybind11::arg("value"));
		cl.def("set_block_uniform", (class easy3d::ShaderProgram * (easy3d::ShaderProgram::*)(const std::string &, const std::string &, const void *)) &easy3d::ShaderProgram::set_block_uniform, "Sets a uniform inside a named block\n Warning: Be careful when using uniform blocks. Please refer to OpenGL Specification Version 4.5\n      (Core Profile) - May 28, 2015 (https://www.opengl.org/registry/doc/glspec45.core.pdf#page=159)\n		In \"Standard Uniform Block Layout\", it says \"If the member is a three-component vector with components\n		consuming N basic machine units, the base alignment is 4N\" (see rule 3 of section 7.6.2.2 in page.159).\n		That means the array stride (the bytes between array elements) is always rounded up to the size of a\n		vec4 (i.e., 16-bytes).\n		So we have to avoid using vec3/mat3 (use vec4/mat4/mat43 instead) in a uniform block. Otherwise,\n		you have to manually pad your structures/arrays out.\n\nC++: easy3d::ShaderProgram::set_block_uniform(const std::string &, const std::string &, const void *) --> class easy3d::ShaderProgram *", pybind11::return_value_policy::automatic, pybind11::arg("blockName"), pybind11::arg("uniformName"), pybind11::arg("value"));
		cl.def("set_block_uniform_array_element", (class easy3d::ShaderProgram * (easy3d::ShaderProgram::*)(const std::string &, const std::string &, int, const void *)) &easy3d::ShaderProgram::set_block_uniform_array_element, "Sets an element of an array of uniforms inside a block\n\nC++: easy3d::ShaderProgram::set_block_uniform_array_element(const std::string &, const std::string &, int, const void *) --> class easy3d::ShaderProgram *", pybind11::return_value_policy::automatic, pybind11::arg("blockName"), pybind11::arg("uniformName"), pybind11::arg("arrayIndex"), pybind11::arg("value"));
		cl.def("bind_texture", [](easy3d::ShaderProgram &o, const std::string & a0, unsigned int const & a1, int const & a2) -> easy3d::ShaderProgram * { return o.bind_texture(a0, a1, a2); }, "", pybind11::return_value_policy::automatic, pybind11::arg("name"), pybind11::arg("tex_id"), pybind11::arg("unit"));
		cl.def("bind_texture", (class easy3d::ShaderProgram * (easy3d::ShaderProgram::*)(const std::string &, unsigned int, int, unsigned int)) &easy3d::ShaderProgram::bind_texture, "C++: easy3d::ShaderProgram::bind_texture(const std::string &, unsigned int, int, unsigned int) --> class easy3d::ShaderProgram *", pybind11::return_value_policy::automatic, pybind11::arg("name"), pybind11::arg("tex_id"), pybind11::arg("unit"), pybind11::arg("tex_target"));
		cl.def("release_texture", [](easy3d::ShaderProgram &o) -> easy3d::ShaderProgram * { return o.release_texture(); }, "", pybind11::return_value_policy::automatic);
		cl.def("release_texture", (class easy3d::ShaderProgram * (easy3d::ShaderProgram::*)(unsigned int)) &easy3d::ShaderProgram::release_texture, "C++: easy3d::ShaderProgram::release_texture(unsigned int) --> class easy3d::ShaderProgram *", pybind11::return_value_policy::automatic, pybind11::arg("tex_target"));
		cl.def("release", (void (easy3d::ShaderProgram::*)() const) &easy3d::ShaderProgram::release, "Ends using the program.\n\nC++: easy3d::ShaderProgram::release() const --> void");
		cl.def("get_attribute_location", (int (easy3d::ShaderProgram::*)(const std::string &) const) &easy3d::ShaderProgram::get_attribute_location, "C++: easy3d::ShaderProgram::get_attribute_location(const std::string &) const --> int", pybind11::arg("name"));
		cl.def("is_uniform_used", (bool (easy3d::ShaderProgram::*)(const std::string &)) &easy3d::ShaderProgram::is_uniform_used, "C++: easy3d::ShaderProgram::is_uniform_used(const std::string &) --> bool", pybind11::arg("name"));
		cl.def("is_attribute_used", (bool (easy3d::ShaderProgram::*)(const std::string &)) &easy3d::ShaderProgram::is_attribute_used, "C++: easy3d::ShaderProgram::is_attribute_used(const std::string &) --> bool", pybind11::arg("name"));
		cl.def("is_program_valid", (bool (easy3d::ShaderProgram::*)() const) &easy3d::ShaderProgram::is_program_valid, "C++: easy3d::ShaderProgram::is_program_valid() const --> bool");
		cl.def("is_program_linked", (bool (easy3d::ShaderProgram::*)() const) &easy3d::ShaderProgram::is_program_linked, "Returns true if program linked, false otherwise.\n\nC++: easy3d::ShaderProgram::is_program_linked() const --> bool");
		cl.def("is_bound", (bool (easy3d::ShaderProgram::*)() const) &easy3d::ShaderProgram::is_bound, "Returns true if the program is being used (i.e., between bind() and  release()).\n\nC++: easy3d::ShaderProgram::is_bound() const --> bool");
		cl.def("shader_info_log", (bool (easy3d::ShaderProgram::*)(std::string &, unsigned int) const) &easy3d::ShaderProgram::shader_info_log, "C++: easy3d::ShaderProgram::shader_info_log(std::string &, unsigned int) const --> bool", pybind11::arg("log"), pybind11::arg("shader"));
		cl.def("program_info_log", (bool (easy3d::ShaderProgram::*)(std::string &) const) &easy3d::ShaderProgram::program_info_log, "C++: easy3d::ShaderProgram::program_info_log(std::string &) const --> bool", pybind11::arg("log"));
		cl.def("print_active_attributes", (void (easy3d::ShaderProgram::*)()) &easy3d::ShaderProgram::print_active_attributes, "C++: easy3d::ShaderProgram::print_active_attributes() --> void");
		cl.def("print_active_uniforms", (void (easy3d::ShaderProgram::*)()) &easy3d::ShaderProgram::print_active_uniforms, "C++: easy3d::ShaderProgram::print_active_uniforms() --> void");
		cl.def("print_active_uniform_blocks", (void (easy3d::ShaderProgram::*)()) &easy3d::ShaderProgram::print_active_uniform_blocks, "C++: easy3d::ShaderProgram::print_active_uniform_blocks() --> void");
		cl.def("load_binary", (bool (easy3d::ShaderProgram::*)(const std::string &)) &easy3d::ShaderProgram::load_binary, "C++: easy3d::ShaderProgram::load_binary(const std::string &) --> bool", pybind11::arg("file_name"));
		cl.def("save_binary", (bool (easy3d::ShaderProgram::*)(const std::string &)) &easy3d::ShaderProgram::save_binary, "C++: easy3d::ShaderProgram::save_binary(const std::string &) --> bool", pybind11::arg("file_name"));
		cl.def_static("load_shader_source", [](const std::string & a0) -> std::string { return easy3d::ShaderProgram::load_shader_source(a0); }, "", pybind11::arg("file_name"));
		cl.def_static("load_shader_source", (std::string (*)(const std::string &, const std::string &)) &easy3d::ShaderProgram::load_shader_source, "Auxiliary function that loads the shader source code from a file.\n \n\n the full path of the file where the source is to be found\n \n\n the include identifier string (e.g., \"#include\")\n\nC++: easy3d::ShaderProgram::load_shader_source(const std::string &, const std::string &) --> std::string", pybind11::arg("file_name"), pybind11::arg("inc_id"));
	}
	{ // easy3d::ShaderManager file:easy3d/renderer/shader_manager.h line:45
		pybind11::class_<easy3d::ShaderManager, std::shared_ptr<easy3d::ShaderManager>> cl(m, "ShaderManager", "Management of shader programs.\n \n\n\n \n make sure to call terminate() to destroy existing programs before the OpenGL context is deleted.");
		cl.def( pybind11::init( [](){ return new easy3d::ShaderManager(); } ) );
		cl.def_static("get_program", (class easy3d::ShaderProgram * (*)(const std::string &)) &easy3d::ShaderManager::get_program, "C++: easy3d::ShaderManager::get_program(const std::string &) --> class easy3d::ShaderProgram *", pybind11::return_value_policy::automatic, pybind11::arg("shader_name"));
		cl.def_static("create_program_from_files", [](const std::string & a0) -> easy3d::ShaderProgram * { return easy3d::ShaderManager::create_program_from_files(a0); }, "", pybind11::return_value_policy::automatic, pybind11::arg("file_base_name"));
		cl.def_static("create_program_from_files", [](const std::string & a0, const class std::vector<struct std::pair<enum easy3d::ShaderProgram::AttribType, std::string> > & a1) -> easy3d::ShaderProgram * { return easy3d::ShaderManager::create_program_from_files(a0, a1); }, "", pybind11::return_value_policy::automatic, pybind11::arg("file_base_name"), pybind11::arg("attributes"));
		cl.def_static("create_program_from_files", [](const std::string & a0, const class std::vector<struct std::pair<enum easy3d::ShaderProgram::AttribType, std::string> > & a1, const class std::vector<std::string> & a2) -> easy3d::ShaderProgram * { return easy3d::ShaderManager::create_program_from_files(a0, a1, a2); }, "", pybind11::return_value_policy::automatic, pybind11::arg("file_base_name"), pybind11::arg("attributes"), pybind11::arg("outputs"));
		cl.def_static("create_program_from_files", (class easy3d::ShaderProgram * (*)(const std::string &, const class std::vector<struct std::pair<enum easy3d::ShaderProgram::AttribType, std::string> > &, const class std::vector<std::string> &, bool)) &easy3d::ShaderManager::create_program_from_files, "C++: easy3d::ShaderManager::create_program_from_files(const std::string &, const class std::vector<struct std::pair<enum easy3d::ShaderProgram::AttribType, std::string> > &, const class std::vector<std::string> &, bool) --> class easy3d::ShaderProgram *", pybind11::return_value_policy::automatic, pybind11::arg("file_base_name"), pybind11::arg("attributes"), pybind11::arg("outputs"), pybind11::arg("geom_shader"));
		cl.def_static("create_program_from_files", [](const std::string & a0, const std::string & a1) -> easy3d::ShaderProgram * { return easy3d::ShaderManager::create_program_from_files(a0, a1); }, "", pybind11::return_value_policy::automatic, pybind11::arg("vert_file_name"), pybind11::arg("frag_file_name"));
		cl.def_static("create_program_from_files", [](const std::string & a0, const std::string & a1, const std::string & a2) -> easy3d::ShaderProgram * { return easy3d::ShaderManager::create_program_from_files(a0, a1, a2); }, "", pybind11::return_value_policy::automatic, pybind11::arg("vert_file_name"), pybind11::arg("frag_file_name"), pybind11::arg("geom_file_name"));
		cl.def_static("create_program_from_files", [](const std::string & a0, const std::string & a1, const std::string & a2, const std::string & a3) -> easy3d::ShaderProgram * { return easy3d::ShaderManager::create_program_from_files(a0, a1, a2, a3); }, "", pybind11::return_value_policy::automatic, pybind11::arg("vert_file_name"), pybind11::arg("frag_file_name"), pybind11::arg("geom_file_name"), pybind11::arg("extra_vert_code"));
		cl.def_static("create_program_from_files", [](const std::string & a0, const std::string & a1, const std::string & a2, const std::string & a3, const std::string & a4) -> easy3d::ShaderProgram * { return easy3d::ShaderManager::create_program_from_files(a0, a1, a2, a3, a4); }, "", pybind11::return_value_policy::automatic, pybind11::arg("vert_file_name"), pybind11::arg("frag_file_name"), pybind11::arg("geom_file_name"), pybind11::arg("extra_vert_code"), pybind11::arg("extra_frag_code"));
		cl.def_static("create_program_from_files", [](const std::string & a0, const std::string & a1, const std::string & a2, const std::string & a3, const std::string & a4, const std::string & a5) -> easy3d::ShaderProgram * { return easy3d::ShaderManager::create_program_from_files(a0, a1, a2, a3, a4, a5); }, "", pybind11::return_value_policy::automatic, pybind11::arg("vert_file_name"), pybind11::arg("frag_file_name"), pybind11::arg("geom_file_name"), pybind11::arg("extra_vert_code"), pybind11::arg("extra_frag_code"), pybind11::arg("extra_geom_code"));
		cl.def_static("create_program_from_files", [](const std::string & a0, const std::string & a1, const std::string & a2, const std::string & a3, const std::string & a4, const std::string & a5, const class std::vector<struct std::pair<enum easy3d::ShaderProgram::AttribType, std::string> > & a6) -> easy3d::ShaderProgram * { return easy3d::ShaderManager::create_program_from_files(a0, a1, a2, a3, a4, a5, a6); }, "", pybind11::return_value_policy::automatic, pybind11::arg("vert_file_name"), pybind11::arg("frag_file_name"), pybind11::arg("geom_file_name"), pybind11::arg("extra_vert_code"), pybind11::arg("extra_frag_code"), pybind11::arg("extra_geom_code"), pybind11::arg("attributes"));
		cl.def_static("create_program_from_files", (class easy3d::ShaderProgram * (*)(const std::string &, const std::string &, const std::string &, const std::string &, const std::string &, const std::string &, const class std::vector<struct std::pair<enum easy3d::ShaderProgram::AttribType, std::string> > &, const class std::vector<std::string> &)) &easy3d::ShaderManager::create_program_from_files, "C++: easy3d::ShaderManager::create_program_from_files(const std::string &, const std::string &, const std::string &, const std::string &, const std::string &, const std::string &, const class std::vector<struct std::pair<enum easy3d::ShaderProgram::AttribType, std::string> > &, const class std::vector<std::string> &) --> class easy3d::ShaderProgram *", pybind11::return_value_policy::automatic, pybind11::arg("vert_file_name"), pybind11::arg("frag_file_name"), pybind11::arg("geom_file_name"), pybind11::arg("extra_vert_code"), pybind11::arg("extra_frag_code"), pybind11::arg("extra_geom_code"), pybind11::arg("attributes"), pybind11::arg("outputs"));
		cl.def_static("create_program_from_codes", [](const std::string & a0, const std::string & a1) -> easy3d::ShaderProgram * { return easy3d::ShaderManager::create_program_from_codes(a0, a1); }, "", pybind11::return_value_policy::automatic, pybind11::arg("vert_code"), pybind11::arg("frag_code"));
		cl.def_static("create_program_from_codes", [](const std::string & a0, const std::string & a1, const std::string & a2) -> easy3d::ShaderProgram * { return easy3d::ShaderManager::create_program_from_codes(a0, a1, a2); }, "", pybind11::return_value_policy::automatic, pybind11::arg("vert_code"), pybind11::arg("frag_code"), pybind11::arg("geom_code"));
		cl.def_static("create_program_from_codes", [](const std::string & a0, const std::string & a1, const std::string & a2, const class std::vector<struct std::pair<enum easy3d::ShaderProgram::AttribType, std::string> > & a3) -> easy3d::ShaderProgram * { return easy3d::ShaderManager::create_program_from_codes(a0, a1, a2, a3); }, "", pybind11::return_value_policy::automatic, pybind11::arg("vert_code"), pybind11::arg("frag_code"), pybind11::arg("geom_code"), pybind11::arg("attributes"));
		cl.def_static("create_program_from_codes", (class easy3d::ShaderProgram * (*)(const std::string &, const std::string &, const std::string &, const class std::vector<struct std::pair<enum easy3d::ShaderProgram::AttribType, std::string> > &, const class std::vector<std::string> &)) &easy3d::ShaderManager::create_program_from_codes, "C++: easy3d::ShaderManager::create_program_from_codes(const std::string &, const std::string &, const std::string &, const class std::vector<struct std::pair<enum easy3d::ShaderProgram::AttribType, std::string> > &, const class std::vector<std::string> &) --> class easy3d::ShaderProgram *", pybind11::return_value_policy::automatic, pybind11::arg("vert_code"), pybind11::arg("frag_code"), pybind11::arg("geom_code"), pybind11::arg("attributes"), pybind11::arg("outputs"));
		cl.def_static("all_programs", (class std::vector<class easy3d::ShaderProgram *> (*)()) &easy3d::ShaderManager::all_programs, "C++: easy3d::ShaderManager::all_programs() --> class std::vector<class easy3d::ShaderProgram *>");
		cl.def_static("terminate", (void (*)()) &easy3d::ShaderManager::terminate, "C++: easy3d::ShaderManager::terminate() --> void");
		cl.def_static("reload", (void (*)()) &easy3d::ShaderManager::reload, "C++: easy3d::ShaderManager::reload() --> void");
	}
}
